# Generated by Django 5.2.2 on 2025-06-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('comum', 'Comum'), ('saudavel', 'Saudável'), ('lowcarb', 'Low Carb')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cardapio_imagens/')),
            ],
        ),
    ]
