# Generated by Django 5.2.2 on 2025-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
