# Generated by Django 5.2.2 on 2025-06-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cardapio_disponivel_alter_cardapio_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='nome',
            new_name='principal',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='preco',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='acompanhamento',
            field=models.CharField(default='Arroz', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='categoria',
            field=models.CharField(choices=[('comum', 'Comum'), ('saudavel', 'Saudável'), ('low_carb', 'Low Carb')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clientes.pedido')),
            ],
        ),
    ]
